---
  general:
    name: 'OpenAICmd'
    version: 'v0.1'
    author: 'Dennis Koehler <dennis.koehler.it@gmail.com>'
    license: 'MIT'
  application:
    apiKey: '<api_key>'
    dataModel: 'gpt-3.5-turbo'
    # optional settings
    tts: false # (windows only)
    # maxTokens: 1200
    # temperature: 0.9
    # maxCompletions: 5
    # sequencesStop: ['hello', 'world']